// Generated by Scripts/sync-content.mjs. Edit content/expansion-150.json.
import Foundation
extension WidgetTemplateKind {
    var newMetadata: ExpansionTemplateMetadata? {
        switch self {
        case .wordDaily: ExpansionTemplateMetadata(title: "每日单词", subtitle: "每天认识一个常用词", category: .learning, symbolName: "character.book.closed.fill", layout: .poster, palette: 0)
        case .wordFlip: ExpansionTemplateMetadata(title: "单词翻面", subtitle: "先回想，再揭晓词义", category: .learning, symbolName: "rectangle.on.rectangle", layout: .poster, palette: 1)
        case .wordReview: ExpansionTemplateMetadata(title: "到期复习", subtitle: "按间隔复习巩固记忆", category: .learning, symbolName: "arrow.clockwise", layout: .list, palette: 2)
        case .wordProgress: ExpansionTemplateMetadata(title: "词汇进度", subtitle: "记录已掌握与待巩固词汇", category: .learning, symbolName: "chart.bar.fill", layout: .gauge, palette: 3)
        case .wordStreak: ExpansionTemplateMetadata(title: "学习连续日", subtitle: "每天一次，积累语言习惯", category: .learning, symbolName: "flame.fill", layout: .timeline, palette: 4)
        case .wordRoots: ExpansionTemplateMetadata(title: "词根拆解", subtitle: "通过词根理解单词结构", category: .learning, symbolName: "textformat.abc", layout: .bento, palette: 5)
        case .wordExample: ExpansionTemplateMetadata(title: "例句卡片", subtitle: "在真实语境中理解词义", category: .learning, symbolName: "text.quote", layout: .poster, palette: 0)
        case .wordSynonyms: ExpansionTemplateMetadata(title: "近义辨析", subtitle: "对照相近表达的语气差异", category: .learning, symbolName: "arrow.left.arrow.right", layout: .list, palette: 1)
        case .wordPhrase: ExpansionTemplateMetadata(title: "短语积累", subtitle: "把常用搭配一起记住", category: .learning, symbolName: "link", layout: .poster, palette: 2)
        case .wordSpelling: ExpansionTemplateMetadata(title: "拼写挑战", subtitle: "回忆英文后再翻面核对", category: .learning, symbolName: "pencil", layout: .poster, palette: 3)
        case .wordListening: ExpansionTemplateMetadata(title: "听读练习", subtitle: "在学习页调用设备语音朗读", category: .learning, symbolName: "speaker.wave.2.fill", layout: .poster, palette: 4)
        case .wordTravel: ExpansionTemplateMetadata(title: "旅行英语", subtitle: "出发前掌握实用表达", category: .learning, symbolName: "airplane", layout: .list, palette: 5)
        case .wordWork: ExpansionTemplateMetadata(title: "职场英语", subtitle: "让会议与邮件表达更自然", category: .learning, symbolName: "briefcase.fill", layout: .list, palette: 0)
        case .wordIELTS: ExpansionTemplateMetadata(title: "雅思词汇", subtitle: "个人词库中的学术表达", category: .learning, symbolName: "graduationcap.fill", layout: .poster, palette: 1)
        case .wordCET: ExpansionTemplateMetadata(title: "四六级词汇", subtitle: "围绕常见阅读主题积累", category: .learning, symbolName: "book.closed.fill", layout: .bento, palette: 2)
        case .wordMistakes: ExpansionTemplateMetadata(title: "易忘词夹", subtitle: "再次练习尚未掌握的词", category: .learning, symbolName: "bookmark.fill", layout: .list, palette: 3)
        case .wordGoal: ExpansionTemplateMetadata(title: "每日词汇目标", subtitle: "小目标也值得认真完成", category: .learning, symbolName: "target", layout: .orbit, palette: 4)
        case .readingNote: ExpansionTemplateMetadata(title: "阅读摘录", subtitle: "留住书里启发你的句子", category: .learning, symbolName: "quote.bubble.fill", layout: .poster, palette: 5)
        case .examSprint: ExpansionTemplateMetadata(title: "考试冲刺", subtitle: "将复习拆成可执行的小步", category: .learning, symbolName: "calendar.badge.clock", layout: .gauge, palette: 0)
        case .languagePassport: ExpansionTemplateMetadata(title: "语言护照", subtitle: "为每个学习阶段盖一枚章", category: .learning, symbolName: "globe", layout: .bento, palette: 1)
        case .packingList: ExpansionTemplateMetadata(title: "旅行清单", subtitle: "出发前检查证件与行李", category: .planner, symbolName: "suitcase.fill", layout: .list, palette: 2)
        case .flightBoard: ExpansionTemplateMetadata(title: "航班便签", subtitle: "手动记录航班与登机时间", category: .time, symbolName: "airplane.departure", layout: .poster, palette: 3)
        case .jetlagClock: ExpansionTemplateMetadata(title: "时差对照", subtitle: "规划跨时区联系时间", category: .time, symbolName: "globe.asia.australia.fill", layout: .timeline, palette: 4)
        case .tripBudget: ExpansionTemplateMetadata(title: "旅途预算", subtitle: "手动记录今日可用预算", category: .finance, symbolName: "wallet.pass.fill", layout: .gauge, palette: 5)
        case .tripJournal: ExpansionTemplateMetadata(title: "旅途一页", subtitle: "用一行文字收藏沿途心情", category: .photos, symbolName: "photo.fill", layout: .poster, palette: 0)
        case .commutePlan: ExpansionTemplateMetadata(title: "通勤计划", subtitle: "手动设置出发与到达时间", category: .planner, symbolName: "tram.fill", layout: .timeline, palette: 1)
        case .cityWishlist: ExpansionTemplateMetadata(title: "城市愿望", subtitle: "为下一座城市留一个位置", category: .daily, symbolName: "map.fill", layout: .list, palette: 2)
        case .weekendRoute: ExpansionTemplateMetadata(title: "周末路线", subtitle: "用三站安排一段慢旅行", category: .planner, symbolName: "location.fill", layout: .list, palette: 3)
        case .breathingGuide: ExpansionTemplateMetadata(title: "呼吸节拍", subtitle: "在应用内跟随舒缓节奏呼吸", category: .health, symbolName: "wind", layout: .orbit, palette: 4)
        case .eyeRest: ExpansionTemplateMetadata(title: "护眼休息", subtitle: "给屏幕之外的风景一点时间", category: .health, symbolName: "eye.fill", layout: .gauge, palette: 5)
        case .stretchBreak: ExpansionTemplateMetadata(title: "伸展间歇", subtitle: "工作间隙动动肩颈", category: .health, symbolName: "figure.flexibility", layout: .poster, palette: 0)
        case .walkInvitation: ExpansionTemplateMetadata(title: "散步邀请", subtitle: "今天也留一段轻松步行", category: .health, symbolName: "figure.walk", layout: .timeline, palette: 1)
        case .moodJournal: ExpansionTemplateMetadata(title: "心情记录", subtitle: "用文字描述此刻的感受", category: .health, symbolName: "face.smiling", layout: .poster, palette: 2)
        case .sleepRitual: ExpansionTemplateMetadata(title: "晚安仪式", subtitle: "睡前给自己一个温柔收尾", category: .health, symbolName: "moon.zzz.fill", layout: .list, palette: 3)
        case .waterSchedule: ExpansionTemplateMetadata(title: "饮水时段", subtitle: "把补水安排在日常节奏里", category: .health, symbolName: "drop.fill", layout: .timeline, palette: 4)
        case .digitalSunset: ExpansionTemplateMetadata(title: "数字日落", subtitle: "手动设定今晚离线时刻", category: .health, symbolName: "sunset.fill", layout: .gauge, palette: 5)
        case .todayThree: ExpansionTemplateMetadata(title: "今日三件事", subtitle: "每天只抓住三个重点", category: .planner, symbolName: "checklist", layout: .list, palette: 0)
        case .deepWork: ExpansionTemplateMetadata(title: "深度工作", subtitle: "为重要工作留一段整块时间", category: .planner, symbolName: "timer", layout: .orbit, palette: 1)
        case .weeklyReflection: ExpansionTemplateMetadata(title: "周末复盘", subtitle: "回顾本周收获与下一步", category: .planner, symbolName: "arrow.triangle.2.circlepath", layout: .list, palette: 2)
        case .readingGoal: ExpansionTemplateMetadata(title: "阅读目标", subtitle: "一本书，一点点往前读", category: .planner, symbolName: "books.vertical.fill", layout: .gauge, palette: 3)
        case .ideaInbox: ExpansionTemplateMetadata(title: "灵感收件箱", subtitle: "把突如其来的想法留住", category: .planner, symbolName: "lightbulb.fill", layout: .list, palette: 4)
        case .deadlineRail: ExpansionTemplateMetadata(title: "截止时间轴", subtitle: "手动记录下一项交付日期", category: .planner, symbolName: "flag.checkered", layout: .timeline, palette: 5)
        case .homeReset: ExpansionTemplateMetadata(title: "居家整理", subtitle: "用小清单整理生活空间", category: .planner, symbolName: "house.fill", layout: .bento, palette: 0)
        case .skillJourney: ExpansionTemplateMetadata(title: "技能旅程", subtitle: "持续记录练习与里程碑", category: .planner, symbolName: "star.fill", layout: .gauge, palette: 1)
        case .dailyPoem: ExpansionTemplateMetadata(title: "诗意日签", subtitle: "收藏自己的短诗与摘录", category: .daily, symbolName: "text.alignleft", layout: .poster, palette: 2)
        case .coffeeMoment: ExpansionTemplateMetadata(title: "咖啡时刻", subtitle: "给忙碌一天留一次停顿", category: .daily, symbolName: "cup.and.saucer.fill", layout: .poster, palette: 3)
        case .petCompanion: ExpansionTemplateMetadata(title: "桌面伙伴", subtitle: "应用内轻动效的陪伴卡片", category: .daily, symbolName: "pawprint.fill", layout: .poster, palette: 4)
        case .colorMood: ExpansionTemplateMetadata(title: "今日色彩", subtitle: "为一天选择一种心情色彩", category: .daily, symbolName: "paintpalette.fill", layout: .bento, palette: 5)
        case .soundtrackDay: ExpansionTemplateMetadata(title: "今日配乐", subtitle: "手动收藏今天的背景音乐", category: .music, symbolName: "music.note", layout: .poster, palette: 0)
        case .memoryCapsule: ExpansionTemplateMetadata(title: "记忆胶囊", subtitle: "给未来的自己留一行小字", category: .photos, symbolName: "archivebox.fill", layout: .poster, palette: 1)
        default: nil
        }
    }
    var sampleValue: String? {
        switch self {
        case .wordDaily: "serendipity"
        case .wordFlip: "resilient"
        case .wordReview: "待复习"
        case .wordProgress: "12 / 40"
        case .wordStreak: "7 天"
        case .wordRoots: "re · build"
        case .wordExample: "Stay curious."
        case .wordSynonyms: "calm / quiet"
        case .wordPhrase: "take a break"
        case .wordSpelling: "c _ r i o u s"
        case .wordListening: "breathe"
        case .wordTravel: "Where is…?"
        case .wordWork: "follow up"
        case .wordIELTS: "perspective"
        case .wordCET: "essential"
        case .wordMistakes: "再想一想"
        case .wordGoal: "10 词"
        case .readingNote: "保持好奇"
        case .examSprint: "21 天"
        case .languagePassport: "第 1 站"
        case .packingList: "3 / 6"
        case .flightBoard: "MU 5101"
        case .jetlagClock: "UTC +8"
        case .tripBudget: "¥280"
        case .tripJournal: "在路上"
        case .commutePlan: "08:20"
        case .cityWishlist: "京都"
        case .weekendRoute: "咖啡 · 公园"
        case .breathingGuide: "吸气 · 呼气"
        case .eyeRest: "20 分钟"
        case .stretchBreak: "伸展一下"
        case .walkInvitation: "15 分钟"
        case .moodJournal: "平静"
        case .sleepRitual: "关灯 · 放松"
        case .waterSchedule: "08 · 12 · 16"
        case .digitalSunset: "22:30"
        case .todayThree: "3 件事"
        case .deepWork: "50 分钟"
        case .weeklyReflection: "本周收获"
        case .readingGoal: "42 / 240"
        case .ideaInbox: "一个新想法"
        case .deadlineRail: "周五交付"
        case .homeReset: "整理 10 分钟"
        case .skillJourney: "第 12 次"
        case .dailyPoem: "风经过窗台"
        case .coffeeMoment: "慢一点"
        case .petCompanion: "你好，今天"
        case .colorMood: "薄荷绿"
        case .soundtrackDay: "Quiet Morning"
        case .memoryCapsule: "写给明天"
        default: nil
        }
    }
}
