import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const additions = JSON.parse(fs.readFileSync(path.join(root, 'content/expansion-200.json'), 'utf8'));
const designs = JSON.parse(fs.readFileSync(path.join(root, 'content/designs.json'), 'utf8'));
const check = process.argv.includes('--check');
const q = JSON.stringify;
function write(file, text) {
  const target = path.join(root, file);
  if (check) {
    if (fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') !== text) throw new Error(`Generated content is stale: ${file}`);
  } else fs.writeFileSync(target, text);
}
write('Shared/Sources/ExpandedContent.swift', `// Generated by Scripts/sync-content.mjs. Edit content/expansion-200.json and content/designs.json.
import Foundation
enum AtelierLayout: String, CaseIterable, Sendable { case orbit, bento, timeline, poster, gauge, list, dial, ticket, constellation, waveform, mosaic, editorial }
struct DesignMetric: Sendable { let label: String; let value: String }
struct TemplateDesign: Sendable {
    let layout: AtelierLayout
    let palette: [String]
    let eyebrow: String
    let value: String
    let caption: String
    let metrics: [DesignMetric]
    let rows: [DesignMetric]
    let progress: Double
    let secondaryProgress: Double
    let series: [Double]
}
extension WidgetTemplateKind {
    var design: TemplateDesign {
        switch self {
${designs.map(d=>`        case .${d.id}: TemplateDesign(layout: .${d.layout}, palette: ${q(d.palette)}, eyebrow: ${q(d.eyebrow)}, value: ${q(d.value)}, caption: ${q(d.caption)}, metrics: [${d.metrics.map(m=>`DesignMetric(label: ${q(m.label)}, value: ${q(m.value)})`).join(', ')}], rows: [${d.rows.map(m=>`DesignMetric(label: ${q(m.label)}, value: ${q(m.value)})`).join(', ')}], progress: ${d.progress}, secondaryProgress: ${d.secondaryProgress}, series: ${q(d.series)})`).join('\n')}
        }
    }
    var newMetadata: ExpansionTemplateMetadata? {
        switch self {
${additions.map(([id,title,subtitle,category,symbol,layout],i)=>`        case .${id}: ExpansionTemplateMetadata(title: ${q(title)}, subtitle: ${q(subtitle)}, category: .${category}, symbolName: ${q(symbol)}, layout: .${layout}, palette: ${i%6})`).join('\n')}
        default: nil
        }
    }
    var sampleValue: String? {
        switch self {
${additions.map(([id,,,,,,value])=>`        case .${id}: ${q(value)}`).join('\n')}
        default: nil
        }
    }
}
`);
write('android/app/src/main/java/com/workdayglow/android/data/ExpandedContent.kt', `// Generated by Scripts/sync-content.mjs.
package com.workdayglow.android.data
val expandedTemplates = listOf(
${additions.map(([id,title,subtitle,category,,layout,value],i)=>`    WidgetTemplate(${q(id)}, ${q(title)}, ${q(subtitle)}, WidgetCategory.${category[0].toUpperCase()+category.slice(1)}, WidgetLayout.${layout[0].toUpperCase()+layout.slice(1)}, ${i%6}, ${q(value)})`).join(',\n')}
)
`);
write('harmony/entry/src/main/ets/model/ExpandedContent.ets', `// Generated by Scripts/sync-content.mjs.
import { WidgetCategory, WidgetLayout, WidgetTemplate } from './WidgetCatalog';
export function getExpandedTemplates(): WidgetTemplate[] { return [
${additions.map(([id,title,subtitle,category,,layout,value],i)=>`  { id: ${q(id)}, title: ${q(title)}, subtitle: ${q(subtitle)}, category: WidgetCategory.${category[0].toUpperCase()+category.slice(1)}, layout: WidgetLayout.${layout[0].toUpperCase()+layout.slice(1)}, palette: ${i%6}, sampleValue: ${q(value)} }`).join(',\n')}
]; }
`);
console.log(`${check ? 'Verified' : 'Generated'} ${additions.length} additions for three platforms.`);
const chunks = Array.from({length: Math.ceil(designs.length / 20)}, (_, i) => designs.slice(i * 20, i * 20 + 20));
write('android/app/src/main/java/com/workdayglow/android/data/AtelierDesign.kt', `// Generated from content/designs.json.
package com.workdayglow.android.data
data class DesignMetric(val label: String, val value: String)
data class AtelierDesign(val title: String, val layout: String, val palette: List<String>, val eyebrow: String, val value: String, val caption: String, val metrics: List<DesignMetric>, val rows: List<DesignMetric>, val progress: Float, val secondaryProgress: Float, val series: List<Float>)
object AtelierCatalog {
    val designs: Map<String, AtelierDesign> = buildList {
${chunks.map((_,i)=>`        addAll(part${i}())`).join('\n')}
    }.associateBy { it.title }
${chunks.map((chunk,i)=>`    private fun part${i}(): List<AtelierDesign> = listOf(\n${chunk.map(d=>`        AtelierDesign(${q(d.title)}, ${q(d.layout)}, listOf(${d.palette.map(q).join(', ')}), ${q(d.eyebrow)}, ${q(d.value)}, ${q(d.caption)}, listOf(${d.metrics.map(m=>`DesignMetric(${q(m.label)}, ${q(m.value)})`).join(', ')}), listOf(${d.rows.map(m=>`DesignMetric(${q(m.label)}, ${q(m.value)})`).join(', ')}), ${d.progress}f, ${d.secondaryProgress}f, listOf(${d.series.map(x=>`${x}f`).join(', ')}))`).join(',\n')}\n    )`).join('\n')}
}
`);
write('harmony/entry/src/main/ets/model/AtelierDesign.ets', `// Generated from content/designs.json.
export interface DesignMetric { label: string; value: string; }
export interface AtelierDesign { title: string; layout: string; palette: string[]; eyebrow: string; value: string; caption: string; metrics: DesignMetric[]; rows: DesignMetric[]; progress: number; secondaryProgress: number; series: number[]; }
const designs: AtelierDesign[] = [
${designs.map(({title,layout,palette,eyebrow,value,caption,metrics,rows,progress,secondaryProgress,series})=>`  ${q({title,layout,palette,eyebrow,value,caption,metrics,rows,progress,secondaryProgress,series})}`).join(',\n')}
];
export function designFor(title: string): AtelierDesign { return designs.find((item: AtelierDesign) => item.title === title) || designs[0]; }
`);
const words = JSON.parse(fs.readFileSync(path.join(root, 'content/words.json'), 'utf8'));
write('Shared/Sources/VocabularySeed.swift', `// Generated by Scripts/sync-content.mjs.
import Foundation
enum VocabularySeed {
    static let words: [VocabularyWord] = [
${words.map(([word,meaning,example])=>`        VocabularyWord(word: ${q(word)}, meaning: ${q(meaning)}, example: ${q(example)})`).join(',\n')}
    ]
}
`);
write('android/app/src/main/java/com/workdayglow/android/data/VocabularySeed.kt', `// Generated by Scripts/sync-content.mjs.
package com.workdayglow.android.data
val vocabularySeed = listOf(
${words.map(([word,meaning,example])=>`    VocabularyWord(${q(word)}, ${q(meaning)}, ${q(example)})`).join(',\n')}
)
`);
write('harmony/entry/src/main/ets/model/VocabularySeed.ets', `// Generated by Scripts/sync-content.mjs.
import { VocabularyWord } from './Vocabulary';
export const vocabularySeed: VocabularyWord[] = [
${words.map(([word,meaning,example])=>`  { word: ${q(word)}, meaning: ${q(meaning)}, example: ${q(example)} }`).join(',\n')}
];
`);
