import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const additions = JSON.parse(fs.readFileSync(path.join(root, 'content/expansion-150.json'), 'utf8'));
const check = process.argv.includes('--check');
const q = JSON.stringify;
function write(file, text) {
  const target = path.join(root, file);
  if (check) {
    if (fs.readFileSync(target, 'utf8') !== text) throw new Error(`Generated content is stale: ${file}`);
  } else fs.writeFileSync(target, text);
}
write('Shared/Sources/ExpandedContent.swift', `// Generated by Scripts/sync-content.mjs. Edit content/expansion-150.json.
import Foundation
extension WidgetTemplateKind {
    var newMetadata: ExpansionTemplateMetadata? {
        switch self {
${additions.map(([id,title,subtitle,category,symbol,layout],i)=>`        case .${id}: ExpansionTemplateMetadata(title: ${q(title)}, subtitle: ${q(subtitle)}, category: .${category}, symbolName: ${q(symbol)}, layout: .${layout}, palette: ${i%6})`).join('\n')}
        default: nil
        }
    }
    var sampleValue: String? {
        switch self {
${additions.map(([id,,,,,,value])=>`        case .${id}: ${q(value)}`).join('\n')}
        default: nil
        }
    }
}
`);
write('android/app/src/main/java/com/workdayglow/android/data/ExpandedContent.kt', `// Generated by Scripts/sync-content.mjs.
package com.workdayglow.android.data
val expandedTemplates = listOf(
${additions.map(([id,title,subtitle,category,,layout,value],i)=>`    WidgetTemplate(${q(id)}, ${q(title)}, ${q(subtitle)}, WidgetCategory.${category[0].toUpperCase()+category.slice(1)}, WidgetLayout.${layout[0].toUpperCase()+layout.slice(1)}, ${i%6}, ${q(value)})`).join(',\n')}
)
`);
write('harmony/entry/src/main/ets/model/ExpandedContent.ets', `// Generated by Scripts/sync-content.mjs.
import { WidgetCategory, WidgetLayout, WidgetTemplate } from './WidgetCatalog';
export function getExpandedTemplates(): WidgetTemplate[] { return [
${additions.map(([id,title,subtitle,category,,layout,value],i)=>`  { id: ${q(id)}, title: ${q(title)}, subtitle: ${q(subtitle)}, category: WidgetCategory.${category[0].toUpperCase()+category.slice(1)}, layout: WidgetLayout.${layout[0].toUpperCase()+layout.slice(1)}, palette: ${i%6}, sampleValue: ${q(value)} }`).join(',\n')}
]; }
`);
console.log(`${check ? 'Verified' : 'Generated'} ${additions.length} additions for three platforms.`);
const words = JSON.parse(fs.readFileSync(path.join(root, 'content/words.json'), 'utf8'));
write('Shared/Sources/VocabularySeed.swift', `// Generated by Scripts/sync-content.mjs.
import Foundation
enum VocabularySeed {
    static let words: [VocabularyWord] = [
${words.map(([word,meaning,example])=>`        VocabularyWord(word: ${q(word)}, meaning: ${q(meaning)}, example: ${q(example)})`).join(',\n')}
    ]
}
`);
write('android/app/src/main/java/com/workdayglow/android/data/VocabularySeed.kt', `// Generated by Scripts/sync-content.mjs.
package com.workdayglow.android.data
val vocabularySeed = listOf(
${words.map(([word,meaning,example])=>`    VocabularyWord(${q(word)}, ${q(meaning)}, ${q(example)})`).join(',\n')}
)
`);
write('harmony/entry/src/main/ets/model/VocabularySeed.ets', `// Generated by Scripts/sync-content.mjs.
import { VocabularyWord } from './Vocabulary';
export const vocabularySeed: VocabularyWord[] = [
${words.map(([word,meaning,example])=>`  { word: ${q(word)}, meaning: ${q(meaning)}, example: ${q(example)} }`).join(',\n')}
];
`);
